INSERT INTO ossinsight_lite_admin.dashboards (name, properties, visibility)
VALUES  ('default', '{"layout": {"gap": 0, "size": []}, "visibility": "public"}', 'public')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO ossinsight_lite_admin.library_items (id, widget_name, properties, visibility)
VALUES  ('about-this-page', 'markdown', '{"markdown": "### About This Page\\n\\n👋 Hi developers, this is my custom dashboard created using [OSSInsight Lite](https://github.com/pingcap/ossinsight-lite).\\n\\nIt summarizes my activities on GitHub through various widgets and allows me to track the open-source projects that interest me.\\n\\n#### Build your own dashboard\\n\\n- Step 1. 🍴Fork the pingcap/ossinsight-lite repoistory\\n\\n- Step 2. ⚙️Setup the data pipeline and deploy the project to Vercel\\n\\n- Step 3. 🎨Add widgets and custom your dashboard\\n\\n[See details](https://github.com/pingcap/ossinsight-lite#how-to-deploy-your-own-10mins)", "title": "About This Page"}', 'public'),
        ('contribution-behavior-percentage', 'db/sql/remote', '{"branch": "main", "name": "contribution-behavior-percentage", "owner": "pingcap", "repo": "ossinsight-lite", "title": "Contribution behavior percentage"}', 'public'),
        ('contribution-monthly', 'db/sql/remote', '{"branch": "main", "name": "contribution-monthly", "owner": "pingcap", "repo": "ossinsight-lite", "title": "Contribution monthly"}', 'public'),
        ('contribution-most-used-languages', 'db/sql/remote', '{"branch": "main", "name": "contribution-most-used-languages", "owner": "pingcap", "repo": "ossinsight-lite", "title": "Contribution languages"}', 'public'),
        ('contribution-pull-request-size-history', 'db/sql/remote', '{"branch": "main", "name": "contribution-pull-request-size-history", "owner": "pingcap", "repo": "ossinsight-lite", "title": "Contribution PR size history"}', 'public'),
        ('contribution-time-distribution', 'db/sql/remote', '{"branch": "main", "name": "contribution-time-distribution", "owner": "pingcap", "repo": "ossinsight-lite", "title": "Contribution time distribution"}', 'public'),
        ('db/sql-1686650509966', 'db/sql', '{"currentDb": "oh-my-github", "sql": "WITH common AS (SELECT DATE_ADD(NOW(), INTERVAL -3 MONTH) AS recent_days),\\n     activities AS (SELECT repo_id, user_id, id AS _id, ''issue'' AS type\\n                    FROM issues\\n                    WHERE created_at > (SELECT recent_days FROM common)\\n                    UNION\\n                    SELECT repo_id, user_id, id AS _id, ''pr'' AS type\\n                    FROM pull_requests\\n                    WHERE created_at > (SELECT recent_days FROM common)\\n                    UNION\\n                    SELECT repo_id, user_id, starred_repos.repo_id AS _id, ''star'' AS type\\n                    FROM starred_repos\\n                    WHERE starred_at > (SELECT recent_days FROM common)\\n                    UNION\\n                    SELECT repo_id, user_id, id AS _id, ''issue_comment'' AS type\\n                    FROM issue_comments\\n                    WHERE created_at > (SELECT recent_days FROM common))\\nSELECT IFNULL(CONCAT(r.owner, ''/'', r.name), ''(unknown)'') AS repo,\\n       COUNT(*)                                          AS activities\\nFROM activities a\\n          JOIN repos r ON a.repo_id = r.id\\nWHERE a.user_id = (SELECT id FROM curr_user)\\nGROUP BY 1 ORDER BY 2 DESC\\nLIMIT 5", "title": "Currently working on", "visualize": {"title": "Untitled", "type": "chart:bar", "x": {"field": "repo", "label": "repo", "type": "category"}, "y": {"field": "activities", "label": "activities", "type": "value"}}}', 'public'),
        ('oh-my-github/avatar', 'oh-my-github/avatar', '{}', 'public'),
        ('oh-my-github/bio', 'oh-my-github/bio', '{}', 'public'),
        ('oh-my-github/username', 'oh-my-github/username', '{}', 'public'),
        ('ossinsight/total-events', 'ossinsight/total-events', '{}', 'public'),
        ('repository-issues-monthly', 'db/sql/remote', '{"branch": "main", "name": "repository-issues-monthly", "owner": "pingcap", "repo": "ossinsight-lite", "title": "Repository issues monthly"}', 'public'),
        ('repository-star-history', 'db/sql/remote', '{"branch": "main", "name": "repository-star-history", "owner": "pingcap", "repo": "ossinsight-lite", "title": "Repository star history"}', 'public')
ON DUPLICATE KEY UPDATE id = id;

INSERT INTO dashboard_items (dashboard_name, item_id, properties)
VALUES  ('default', 'about-this-page', '{"layout": {"lg": {"h": 7, "i": "about-this-page", "moved": false, "static": false, "w": 6, "x": 1, "y": 5}, "md": {"h": 7, "i": "about-this-page", "moved": false, "static": false, "w": 7, "x": 0, "y": 5}, "sm": {"h": 9, "i": "about-this-page", "moved": false, "static": false, "w": 6, "x": 0, "y": 4}}}'),
        ('default', 'contribution-behavior-percentage', '{"layout": {"lg": {"h": 5, "i": "contribution-behavior-percentage", "moved": false, "static": false, "w": 5, "x": 9, "y": 0}, "md": {"h": 5, "i": "contribution-behavior-percentage", "moved": false, "static": false, "w": 4, "x": 8, "y": 0}, "sm": {"h": 5, "i": "contribution-behavior-percentage", "moved": false, "static": false, "w": 6, "x": 0, "y": 13}}}'),
        ('default', 'contribution-monthly', '{"layout": {"lg": {"h": 7, "i": "contribution-monthly", "moved": false, "static": false, "w": 5, "x": 7, "y": 5}, "md": {"h": 7, "i": "contribution-monthly", "moved": false, "static": false, "w": 5, "x": 7, "y": 5}, "sm": {"h": 6, "i": "contribution-monthly", "moved": false, "static": false, "w": 6, "x": 0, "y": 18}}}'),
        ('default', 'contribution-most-used-languages', '{"layout": {"lg": {"h": 5, "i": "contribution-most-used-languages", "moved": false, "static": false, "w": 4, "x": 5, "y": 0}, "md": {"h": 5, "i": "contribution-most-used-languages", "moved": false, "static": false, "w": 4, "x": 4, "y": 0}, "sm": {"h": 5, "i": "contribution-most-used-languages", "moved": false, "static": false, "w": 6, "x": 0, "y": 24}}}'),
        ('default', 'contribution-pull-request-size-history', '{"layout": {"lg": {"h": 7, "i": "contribution-pull-request-size-history", "moved": false, "static": false, "w": 6, "x": 17, "y": 5}, "md": {"h": 7, "i": "contribution-pull-request-size-history", "moved": false, "static": false, "w": 6, "x": 6, "y": 18}, "sm": {"h": 6, "i": "contribution-pull-request-size-history", "moved": false, "static": false, "w": 6, "x": 0, "y": 29}}}'),
        ('default', 'contribution-time-distribution', '{"layout": {"lg": {"h": 5, "i": "contribution-time-distribution", "moved": false, "static": false, "w": 9, "x": 14, "y": 0}, "md": {"h": 6, "i": "contribution-time-distribution", "moved": false, "static": false, "w": 12, "x": 0, "y": 12}, "sm": {"h": 6, "i": "contribution-time-distribution", "moved": false, "static": false, "w": 6, "x": 0, "y": 35}}}'),
        ('default', 'db/sql-1686650509966', '{"layout": {"lg": {"h": 7, "i": "db/sql-1686650509966", "moved": false, "static": false, "w": 5, "x": 12, "y": 5}, "md": {"h": 7, "i": "db/sql-1686650509966", "moved": false, "static": false, "w": 6, "x": 0, "y": 18}, "sm": {"h": 7, "i": "db/sql-1686650509966", "moved": false, "static": false, "w": 6, "x": 0, "y": 41}}}'),
        ('default', 'oh-my-github/avatar', '{"layout": {"lg": {"h": 3, "i": "oh-my-github/avatar", "moved": false, "static": false, "w": 2, "x": 1, "y": 0}, "md": {"h": 3, "i": "oh-my-github/avatar", "moved": false, "static": false, "w": 2, "x": 0, "y": 0}, "sm": {"h": 4, "i": "oh-my-github/avatar", "moved": false, "static": false, "w": 2, "x": 0, "y": 0}}}'),
        ('default', 'oh-my-github/bio', '{"layout": {"lg": {"h": 2, "i": "oh-my-github/bio", "moved": false, "static": false, "w": 4, "x": 1, "y": 3}, "md": {"h": 2, "i": "oh-my-github/bio", "moved": false, "static": false, "w": 4, "x": 0, "y": 3}, "sm": {"h": 3, "i": "oh-my-github/bio", "moved": false, "static": false, "w": 4, "x": 2, "y": 1}}}'),
        ('default', 'oh-my-github/username', '{"layout": {"lg": {"h": 3, "i": "oh-my-github/username", "moved": false, "static": false, "w": 2, "x": 3, "y": 0}, "md": {"h": 3, "i": "oh-my-github/username", "moved": false, "static": false, "w": 2, "x": 2, "y": 0}, "sm": {"h": 1, "i": "oh-my-github/username", "moved": false, "static": false, "w": 4, "x": 2, "y": 0}}}')
ON DUPLICATE KEY UPDATE dashboard_name = dashboard_name;