DROP USER IF EXISTS '${READONLY_USERNAME}'@'%';
CREATE USER '${READONLY_USERNAME}'@'%' IDENTIFIED BY '${READONLY_PASSWORD}';
GRANT SELECT, SHOW DATABASES, SHOW VIEW ON *.* TO '${READONLY_USERNAME}'@'%';

FLUSH PRIVILEGES;
